### ISSUE TITLE
Visualize generic modules (hierarchical)

### ISSUE THREAD

**Issue by Dev1an** [Quite-nice/Visualisation#10]
Make a realtime hierarchical visualization of the modules

**Comment by jeroenbe** [comment]
Initial draft in genericui branch

**Comment by Dev1an** [comment]
I think it's more useful to show **sent** events instead of **received** events for a module.

**Comment by Dev1an** [comment]
Take for example the github mock data (I know the mock data is not well structured now, but I will change it next week).

If you only show the module's sent messages, you will see the commits in the branch module and the issues in the issues module, instead of the commits and the issues together in both the branch module and the issues module.

**Comment by jeroenbe** [comment]
I understand your argument, yet, it is one regarding an implementation. Since we're still talking about the `generic-ui`, I think it's best to nuance the usefulness of any of the additions to this ui. When we're building a GitHub specific visualisation (built upon the `generic-ui`), it might indeed be more useful to only show the sent messages.

**Comment by maccradar** [comment]
> On 03 Jun 2016, at 23:15, Jeroen notifications@github.com wrote:
> 
> I understand your argument, yet, it is one regarding an implementation. Since we're still talking about the generic-ui, I think it's best to nuance the usefulness of any of the additions to this ui. When we're building a GitHub specific visualisation (built upon the generic-ui), it might indeed be more useful to only show the sent messages.

In the general / generic case, each entity should show both input and output, so both incoming and outgoing messages.

**Comment by Dev1an** [comment]
The point I was trying to make is:
1. It might be more readable if you only show each message once, especially when there are lots of messages per second. (a message is sent once, and can be received multiple times).
2. We don't know for sure when / if a message is received by another node. In the case of the Zyre mediator we can **assume** that shouts are received by every other node in the group to which a message was shout but we do not know for sure.

The Github story was only an example.

**Comment by maccradar** [comment]
Rule of thumb in programming: don't optimise (too early). A generic version shows all messages, a policy could be to filter out in or outgoing, specific groups, peer to peer, message types,... Aggregation is also a policy that can  enhance readability if a lot of messages are sent per second.

What we need for one of our projects is to identity bottlenecks. Aggregation over time or showing the cumulative in a clever way is a must have here. In case of a force graph you could let de sphere size grow is a node is sending or receiving a lot of messages.

On 04 Jun 2016, at 20:45, Damiaan Dufaux <notifications@github.com<mailto:notifications@github.com>> wrote:

The point I was trying to make is:
1.  It might be more readable if you only show each message once, especially when there are lots of messages per second. (a message is sent once, and can be received multiple times).
2.  We don't know for sure when / if a message is received by another node. In the case of the Zyre mediator we can assume that shouts are received by every other node in the group to which a message was shout but we do not know for sure.

The Github story was only an example.

##

**Comment by Dev1an** [comment]
Module and submodule visualization implemented.
Here you see an overview of all the top-level modules:
![root module](https://cloud.githubusercontent.com/assets/3158324/15985021/0313b9d8-2fe0-11e6-9486-39b295d5cc75.png)

And if you click on the websocket mediator, you get a detail view of that module and its submodules.

![websocket mediator](https://cloud.githubusercontent.com/assets/3158324/15985020/01335f38-2fe0-11e6-8d01-64e72f3d9150.png)

There is no restriction on how many levels of submodules you can have.

**Comment by Dev1an** [comment]
Also added breadcrumbs to navigate back to an ancestor module
![breadcrumbs](https://cloud.githubusercontent.com/assets/3158324/15986808/d10d042a-3012-11e6-9cf8-10fa7e337ea1.png)

**Comment by Dev1an** [comment]
Added a JsonView to inspect the events
<img width="402" alt="jsonview" src="https://cloud.githubusercontent.com/assets/3158324/16001843/c45af032-3154-11e6-90e4-ea50b70664f3.png">
