### ISSUE TITLE
Define standard DetailPage for Module

### ISSUE THREAD

**Issue by jeroenbe** [Quite-nice/Visualisation#23]
# Define standard `DetailPage` for `Module`

When browsing a `Module` it's rather confusing/ugly to see all `DetailPage`s folded in. It would be nice to have a default-go-to `DetailPage` defined for a `Module`. Whenever the specific `Module` is browsed to, this default `DetailPage` should be opened.
## Why?

For one, it makes the app more consistent. We could define a certain visualisation design standard to which we default when browsing `Module`s or `Event`s. 
## How?

Right now, the way to browse a `DetailPage` is done with a querystring. This querystring expects a parameter `page`. We could let the generic link of the `MiniView` of the specific `Module` point to the `DetailView` with this querystring filled in. If we lack a `page`-parameter, the querystring would be as follows: `/module/id?page=`, this shouldn't pose a problem since this just means no `Template` gets rendered.

**Comment by Dev1an** [comment]
I completely agree that we need this. I'm not so sure about the "how" part but feel free to add a pull request.

**Comment by jeroenbe** [comment]
Great! Could you elaborate on your stance regarding the _how_ part?

**Comment by Dev1an** [comment]
I think it would be great if there is always one tab (`DetailPage`) selected, except when the module does not have `DetailPage`s.

With your suggestion it is still possible to have a module with multiple `DetailPage`s of which none are selected. The solution I had in mind was to render the first `DetailPage` when there is no identifier in the queryString.
