### ISSUE TITLE
 Create new empty Meteor application 

### ISSUE THREAD

**Issue by Kymer** [Quite-nice/Visualisation#5]
Create a fresh 1.3 Meteor application following the folder structure as outlined in the [official guide](http://guide.meteor.com/structure.html).

**Comment by Kymer** [comment]
This link to the [1.3 migration guide](http://guide.meteor.com/1.3-migration.html) might come come in handy, so I'll leave it here for future reference. There are some handy links on the bottom of that page.

**Comment by Dev1an** [comment]
A test from within favro
