### ISSUE TITLE
Look into different testing libraries

### ISSUE THREAD

**Issue by Kymer** [Quite-nice/Visualisation#7]
As previously discussed we will try to work as _test-driven_ as possible. Meteor 1.3 has a heavy focus on testing. More info can be found in the [official guide](http://guide.meteor.com/testing.html).

There are different testing frameworks that can be used with Meteor:
- [Mocha](https://github.com/mad-eye/meteor-mocha-web)
- [Velocity](https://github.com/meteor-velocity/velocity) (official link seems to be down: http://velocity.meteor.com)
- [Laika](http://arunoda.github.io/laika/)
- [Jasmine](https://meteor-testing.readme.io/docs/getting-started)

This might be worth watching: [NPM and Testing in Meteor 1.3](https://www.youtube.com/watch?v=sqOfEgvpXt0), an official Meteor Devshop talk.

**Comment by Kymer** [comment]
Mocha seems to be [recommended](http://guide.meteor.com/testing.html#mocha).

**Comment by Dev1an** [comment]
Then I suggest to use mocha with chai. Reopen this issue if you encounter problems with it.
